In [58]:
# 1. What is a Decision Tree?

# A Decision Tree is a supervised machine-learning model used for classification and regression.
# It splits the data into branches based on conditions to predict a target value.

# A tree consists of:

# Root Node – The starting feature for splitting

# Internal Nodes – Feature-based decision points

# Leaf Nodes – Final prediction (class label or value)

# Branches – Outcomes of a decision

## Project Objective

This project is a small practice-based machine learning project
focused on understanding how Decision Tree models work.

It uses a simple dataset to predict whether an employee’s salary
is greater than 100K based on company, job role, and education level.

The main goal is to learn the basic steps of building,
training, and evaluating a classification model using Python.

In [59]:
import pandas as pd

In [60]:
df = pd.read_csv('salaries.csv')

In [61]:
df.shape

(16, 4)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes

In [63]:
df.describe()

       salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [64]:
df.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [67]:
inputs = df.drop('salary_more_then_100k',axis='columns')

In [68]:
target = df['salary_more_then_100k']

In [69]:
from sklearn.preprocessing import LabelEncoder # LabelEncoder converts categorical labels into numeric values,other option OneHotEncoder
lbl_company = LabelEncoder()
lbl_job = LabelEncoder()
lbl_degree = LabelEncoder()

In [70]:
inputs['company_n'] = lbl_company.fit_transform(inputs['company'])
inputs['job_n'] = lbl_job.fit_transform(inputs['job'])
inputs['degree_n'] = lbl_degree.fit_transform(inputs['degree'])

In [71]:
inputs

       company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [72]:
inputs_numeric = inputs.drop(['company','job','degree'],axis='columns') # Keeping only numeric columns

In [73]:
inputs_numeric

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [74]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [75]:
# Splitting data into training/testing sets:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    inputs_numeric, target, test_size=0.2, random_state=42
)

In [76]:
from sklearn import tree
model = tree.DecisionTreeClassifier(random_state=42)

In [77]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [78]:
# DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
           # max_features=None, max_leaf_nodes=None,
           # min_impurity_decrease=0.0, min_impurity_split=None,
           # min_samples_leaf=1, min_samples_split=2,
           # min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           # splitter='best')

In [79]:
accuracy = model.score(X_test, y_test)

In [80]:
print("Model Accuracy:", accuracy)

Model Accuracy: 0.75

In [81]:
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [82]:
inputs_numeric

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [83]:
# Making simple predictions using numeric values

# Format: [company_n, job_n, degree_n]

# Example 1: Google, Computer Programmer, Master's
prediction1 = model.predict([[2, 1, 1]])

# Example 2: ABC Pharma, Sales Executive, Bachelor's
prediction2 = model.predict([[0, 2, 0]])

# Example 3: facebook, computer programmer, masters's
prediction3 = model.predict([[1, 1 , 1]])

print(prediction1)
print(prediction2)
print(prediction3)

# 2 out of 3 correct → ~66% → matches your ~75% accuracy.

[0]
[0]
[1]

D:\Python\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
D:\Python\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
D:\Python\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

### Final Conclusion:
The model achieved around 75% accuracy on the test data.
Because the dataset is very small, the predictions are not always reliable.

Overall, this project helped in understanding the basic steps
of building, training, and using a machine learning classification model.
Using more data can help improve the model in the future.

In [84]:
import joblib # Dump Model

In [85]:
joblib.dump(model, "salary_model.pkl")
joblib.dump(lbl_company, "company_encoder.pkl")
joblib.dump(lbl_job, "job_encoder.pkl")
joblib.dump(lbl_degree, "degree_encoder.pkl")

['degree_encoder.pkl']